sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: ${SKY_ALIOSS_ENDPOINT}
    access-key-id: ${SKY_ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${SKY_ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: ${SKY_ALIOSS_BUCKET_NAME}
